import {createHash} from 'node:crypto';
import {cards} from '../src/data/cards.mjs';
import {guides} from '../src/data/guides.mjs';
import {artwork} from '../src/card-view.mjs';
import {cardSlug,cardGroupLabel,suitInfo} from '../src/data/card-directory.mjs';
import {mkdir,writeFile,cp,rm,readFile,readdir} from 'node:fs/promises';
import {readings,primary,secondary,tertiary} from '../src/data/readings.mjs';
const origin=(process.env.SITE_URL||'https://pickacard.jijiminseo.chatgpt.site').replace(/\/$/,'');
const basePath=(process.env.BASE_PATH||'').trim().replace(/^\/+|\/+$/g,'');
const publicBase=basePath?`/${basePath}`:'';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readingEmoji={love:'💗',reunion:'🔁',breakup:'🥀',feelings:'💭',contact:'💌','reunion-timing':'⏳','yes-no':'🔮',today:'☀️',job:'💼',money:'💰',work:'🧑‍💻',study:'📚'};
const faq=items=>`<div class="faq">${items.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;
const faqList=items=>`<div class="faq-list">${items.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;
const tile=(slug,small=false)=>{const r=readings[slug],i=Object.keys(readings).indexOf(slug)+1;return `<a class="reading-tile ${small?'small':''}" href="/tarot/${slug}/"><span class="tile-head"><span class="tile-icon" aria-hidden="true">${readingEmoji[slug]||r.mark}</span><span class="tile-index">${String(i).padStart(2,'0')} / ${slug==='yes-no'?'1–3':r.positions.length} CARDS</span></span><span class="tile-top">${r.name}</span><span class="tile-bottom">${r.tagline}</span><span class="tile-link">리딩 펼치기</span></a>`};
const cardPath=card=>`/cards/${cardSlug(card)}/`;
const cardImage=card=>`/artwork/${artwork[card.id]}.webp`;
const cardSmallImage=card=>`/artwork/${artwork[card.id]}-small.webp`;
const cardTile=card=>`<a class="card-library-tile" href="${cardPath(card)}"><span class="card-library-thumb"><img src="${cardSmallImage(card)}" width="192" height="288" loading="lazy" decoding="async" alt="${esc(card.koreanName)} 타로 카드"></span><span class="card-library-copy"><small>${esc(cardGroupLabel(card))}</small><strong>${esc(card.koreanName)}</strong><span>${esc(card.name)}</span><em>${card.keywords.map(esc).join(' · ')}</em></span></a>`;
const cardTopicRows=card=>[
 ['연애운',card.love,'/tarot/love/'],
 ['재회운',card.reunion,'/tarot/reunion/'],
 ['상대방 속마음',card.feelings,'/tarot/feelings/'],
 ['연락운',card.contact,'/tarot/contact/'],
 ['이별운',card.breakup,'/tarot/breakup/'],
 ['시기',card.timing,'/tarot/reunion-timing/']
];
const cardDetailBody=(card,index)=>{
 const previous=cards[(index-1+cards.length)%cards.length],next=cards[(index+1)%cards.length];
 const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[
  {'@type':'ListItem',position:1,name:'Pick a Card',item:`${origin}/`},
  {'@type':'ListItem',position:2,name:'타로 카드 78장 사전',item:`${origin}/cards/`},
  {'@type':'ListItem',position:3,name:`${card.koreanName} ${card.name}`,item:`${origin}${cardPath(card)}`}
 ]};
 return `<main id="main" class="card-dictionary-page"><nav class="card-breadcrumb" aria-label="현재 위치"><a href="/">홈</a><span>›</span><a href="/cards/">타로 카드 78장</a><span>›</span><span>${esc(card.koreanName)}</span></nav><article class="card-dictionary-detail"><section class="card-dictionary-hero"><div class="card-dictionary-art"><img src="${cardImage(card)}" srcset="${cardSmallImage(card)} 192w, ${cardImage(card)} 384w" sizes="(max-width:720px) 46vw, 250px" width="384" height="576" decoding="async" alt="${esc(card.koreanName)} ${esc(card.name)} 타로 카드"></div><div class="card-dictionary-intro"><span class="section-kicker">${esc(cardGroupLabel(card))}</span><h1>${esc(card.koreanName)} <span>${esc(card.name)}</span></h1><p class="card-dictionary-lead">${esc(card.upright)}</p><div class="card-keyword-row">${card.keywords.map(k=>`<span>${esc(k)}</span>`).join('')}</div></div></section><section class="card-meaning-overview" aria-labelledby="meaning-overview-title"><div class="card-section-heading"><span class="section-kicker">Card meaning</span><h2 id="meaning-overview-title">${esc(card.koreanName)} 카드 뜻</h2><p>같은 카드도 방향과 질문에 따라 강조되는 의미가 달라져요. 먼저 정방향과 역방향의 중심을 비교해보세요.</p></div><div class="card-meaning-grid"><article><span>UPRIGHT · 정방향</span><h3>정방향으로 나오면</h3><p>${esc(card.upright)}</p></article><article><span>REVERSED · 역방향</span><h3>역방향으로 나오면</h3><p>${esc(card.reversed)}</p></article><article class="card-advice-box"><span>ONE THING TO KEEP</span><h3>이 카드의 핵심 조언</h3><p>${esc(card.advice)}</p></article></div></section><section class="card-topic-section" aria-labelledby="topic-reading-title"><div class="card-section-heading"><span class="section-kicker">By question</span><h2 id="topic-reading-title">질문별로 읽으면</h2><p>연애, 재회, 속마음처럼 궁금한 주제에 따라 같은 상징을 조금 다르게 읽을 수 있어요.</p></div><div class="card-topic-grid">${cardTopicRows(card).map(([title,text,href])=>`<article><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div><a href="${href}">${esc(title)} 타로 보기 →</a></article>`).join('')}</div></section><section class="card-dictionary-cta"><span aria-hidden="true">🔮</span><div><strong>이 카드가 내 질문에서는 어떻게 읽힐까요?</strong><p>카드 뜻을 확인했다면 직접 카드를 골라 지금의 흐름으로 이어서 읽어보세요.</p></div><a class="button primary" href="/#readings">무료 타로 고르기 →</a></section><nav class="card-prev-next" aria-label="다른 타로 카드"><a href="${cardPath(previous)}"><small>← 이전 카드</small><strong>${esc(previous.koreanName)}</strong><span>${esc(previous.name)}</span></a><a href="/cards/" class="card-all-link"><small>78장 전체</small><strong>카드 사전</strong><span>모든 카드 보기</span></a><a href="${cardPath(next)}"><small>다음 카드 →</small><strong>${esc(next.koreanName)}</strong><span>${esc(next.name)}</span></a></nav></article><script type="application/ld+json">${JSON.stringify(breadcrumb).replace(/</g,'\\u003c')}</script></main>`;
};
const footer=`<footer><div class="footer-grid"><div><a class="brand" href="/">Pick a Card</a><p>카드 한 장에서 시작하는,<br>나를 이해하는 시간.</p></div><div><h3>타로 리딩</h3>${primary.map(s=>`<a href="/tarot/${s}/">${readings[s].name}</a>`).join('')}<a href="/tarot/today/">오늘의 카드</a></div><div><h3>읽을거리와 안내</h3><a href="/guide/">타로 가이드</a><a href="/cards/">타로 카드 78장</a><a href="/faq/">자주 묻는 질문</a><a href="/about/">이용 안내 · 서비스 고지</a><a href="/privacy/">개인정보 안내</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Pick a Card</span><span>한국어</span></div></footer>`;
const page=(title,description,path,body,faqs=[])=>`<!doctype html><html lang="ko"><head><meta charset="UTF-8">${path==='/404'?'<meta name="robots" content="noindex">':''}<meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin}${path}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:url" content="${origin}${path}"><meta name="theme-color" content="#ffffff"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#23272b"/><path d="M16 6v20M6 16h20M9 9l14 14M23 9L9 23" stroke="#f1b5c7" stroke-width="3"/></svg>')}"><link rel="stylesheet" href="/style.css">${faqs.length?`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}).replace(/</g,'\\u003c')}</script>`:''}</head><body><a class="skip" href="#main">본문으로 건너뛰기</a><header><a href="/" class="brand" aria-label="pick a card 홈">Pick a Card<small>TAROT READING</small></a><nav aria-label="주 메뉴"><a href="/#readings">타로 보기</a><a href="/tarot/today/">오늘의 카드</a><a href="/guide/">타로 가이드</a><a href="/faq/">FAQ</a></nav></header>${body}${footer}<script type="module" src="/src/app.mjs"></script></body></html>`;
const homeFaq=[
['이용하는 데 비용이 드나요?','아니요. 현재 제공되는 타로 리딩은 가입이나 결제 없이 무료로 이용할 수 있어요.'],
['질문을 꼭 입력해야 하나요?','대부분의 리딩은 마음속으로 질문을 떠올리기만 해도 됩니다. YES/NO 타로만 질문 입력이 필요해요.'],
['같은 질문을 여러 번 봐도 되나요?','볼 수는 있지만, 같은 질문을 연달아 반복하기보다는 한 번의 리딩을 충분히 읽고 다시 궁금해졌을 때 새로 펼쳐보는 편을 추천해요.'],
['오늘의 타로는 언제 바뀌나요?','사용 중인 기기의 현지 날짜를 기준으로 자정이 지나면 새로운 오늘의 카드를 뽑을 수 있어요.']
];
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('src','dist/src',{recursive:true});await cp('public','dist',{recursive:true});
await writeFile('dist/index.html',page('무료 타로 · 연애운, 재회운, 취업운, 금전운 | pick a card','지금 마음에 남는 질문 하나. 연애운, 재회운, 상대방 속마음부터 취업운, 금전운, 직장운까지 직접 고르는 12가지 무료 타로.','/',`<main id="main"><section class="home-intro"><div class="kicker">PICK A CARD · A QUIET MOMENT</div><h1>마음에 걸리는<br>질문이 있나요?</h1><p>카드를 고르고, 지금의 흐름을 천천히 읽어보세요.<br>당신의 질문에 열두 가지 리딩을 건넵니다.</p><div class="quiet-label">가입 없이 · 언제나 무료</div></section><section id="readings" class="readings-section"><div class="section-heading"><h2>마음이 향하는 질문</h2><span>LOVE & RELATIONSHIPS</span></div><div class="primary-grid">${primary.map(s=>tile(s)).join('')}</div><div class="section-heading secondary-heading"><h2>조금 더 궁금하다면</h2><span>A LITTLE MORE</span></div><div class="secondary-grid">${secondary.map(s=>tile(s,true)).join('')}</div><div class="section-heading secondary-heading tertiary-heading"><h2>다른 고민이 있다면</h2><span>WORK & EVERYDAY</span></div><div class="secondary-grid tertiary-grid">${tertiary.map(s=>tile(s,true)).join('')}</div></section><section class="about"><div class="about-copy"><span class="kicker">ABOUT THE READING</span><h2>미래를 정하는 답보다,<br>지금을 이해하는 질문.</h2><p>Pick a Card는 78장의 상징을 질문과 스프레드에 맞춰 읽는 무료 타로예요. 카드를 직접 고르고, 정방향과 역방향이 만드는 서로 다른 흐름을 천천히 살펴보세요.</p><a class="about-link" href="/guide/">타로 가이드 둘러보기 →</a></div><div class="about-grid"><article><span class="about-icon" aria-hidden="true">🃏</span><div><b>${cards.length} cards</b><p>메이저와 마이너 전체 덱으로 읽어요.</p></div></article><article><span class="about-icon" aria-hidden="true">💗</span><div><b>12 readings</b><p>연애, 재회부터 취업·금전·학업까지.</p></div></article><article><span class="about-icon" aria-hidden="true">↕️</span><div><b>Upright & reversed</b><p>같은 카드도 방향에 따라 다르게 읽어요.</p></div></article></div></section><section class="home-explainer" aria-labelledby="reading-notes-title"><div class="section-heading"><span class="section-kicker">Reading notes</span><h2 id="reading-notes-title">조금 더 깊이 읽고 싶다면</h2><p>카드의 방향, 아르카나, 질문을 만드는 방법처럼 리딩을 더 재미있게 읽는 데 도움이 되는 짧은 가이드예요.</p></div><div class="home-info-grid">${guides.slice(0,3).map(g=>`<a class="home-info-card" href="/guide/${g.slug}/"><h3>${g.title}</h3><p>${g.intro}</p><span>읽어보기 →</span></a>`).join('')}</div><div class="explainer-links"><a class="explainer-link" href="/guide/">모든 타로 가이드 보기 →</a><a class="explainer-link" href="/cards/">78장 타로 카드 사전 보기 →</a></div></section><section class="home-faq" aria-labelledby="home-faq-title"><div class="section-heading"><span class="section-kicker">Questions</span><h2 id="home-faq-title">Pick a Card FAQ</h2></div><div class="faq-list">${homeFaq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div></section></main>`,homeFaq));
for(const [slug,r] of Object.entries(readings)){
const path=`/tarot/${slug}/`;await mkdir(`dist${path}`,{recursive:true});
const body=`<main id="main" data-reading="${slug}"><a class="back-link" href="/">모든 타로</a><section class="reading-intro"><span class="kicker">${r.eyebrow}</span><h1>${r.name}</h1><p class="lead">${r.tagline}</p><p>${r.intro}</p><div class="reading-meta"><span>${slug==='yes-no'?'1–3':r.positions.length}장의 카드</span><span>무료 리딩</span><span>정·역방향</span></div></section><div class="ad-slot" data-ad-placement="before-selection" hidden></div><section id="reading-app" aria-label="카드 리딩"><form id="question-form" class="question-panel"><div class="panel-heading"><span class="step-label">01 / YOUR QUESTION</span><h2>질문을 천천히 떠올려 주세요.</h2><p>${r.question}</p></div>${slug!=='today'?`<label for="question">나의 질문 <span>${slug==='yes-no'?'필수':'선택 · 마음속으로 떠올려도 좋아요'}</span></label><textarea id="question" name="question" maxlength="300" rows="2" placeholder="${r.question}" ${slug==='yes-no'?'required':''}></textarea><p class="privacy-note">질문은 저장하거나 외부로 전송하지 않아요.</p>`:''}${slug==='yes-no'?'<fieldset><legend>몇 장의 카드를 뽑을까요?</legend><div class="count-options">'+[1,2,3].map(n=>`<label><input type="radio" name="count" value="${n}" ${n===3?'checked':''}><span>${n}장</span></label>`).join('')+'</div></fieldset>':''}<button class="button primary" type="submit">${slug==='today'?'오늘의 카드 만나기':'카드 고르기'}<span aria-hidden="true">✳</span></button><p id="form-error" role="alert"></p></form><noscript><p>카드 선택에는 JavaScript가 필요합니다. 아래에서 스프레드 안내와 자주 묻는 질문을 읽을 수 있습니다.</p></noscript></section><section class="spread-info"><div class="spread-head"><span class="section-kicker">The spread</span><h2>${r.name}, 이렇게 읽어요</h2><p>${r.explanation}</p></div><ol>${r.positions.map((p,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><div><h3>${p.label}</h3><p>${p.lens}</p></div></li>`).join('')}</ol></section><section class="home-faq reading-faq" aria-labelledby="${slug}-faq-title"><div class="section-heading"><span class="section-kicker">Questions</span><h2 id="${slug}-faq-title">${r.name} 자주 묻는 질문</h2></div>${faqList(r.faq)}</section></main>`;
await writeFile(`dist${path}index.html`,page(`${r.name} 무료 타로 | ${r.tagline} · pick a card`,r.description,path,body,r.faq));}
const majorCards=cards.filter(card=>card.arcana==='major');
const minorGroups=Object.keys(suitInfo).map(suit=>[suit,cards.filter(card=>card.suit===suit)]);
const cardHubBody=`<main id="main" class="card-library-page"><section class="card-library-hero"><span class="section-kicker">Tarot card dictionary</span><h1>타로 카드 78장 의미 사전</h1><p>메이저 아르카나 22장과 마이너 아르카나 56장을 한 장씩 살펴보세요. 정방향·역방향 뜻부터 연애, 재회, 속마음, 연락, 시기 해석까지 정리했습니다.</p><nav class="card-library-jump" aria-label="카드 분류 바로가기"><a href="#major">메이저 22</a>${minorGroups.map(([suit])=>`<a href="#${suit}">${suitInfo[suit].emoji} ${suitInfo[suit].ko} 14</a>`).join('')}</nav></section><section class="card-library-group" id="major"><div class="card-library-group-head"><div><span class="section-kicker">Major Arcana</span><h2>메이저 아르카나 22장</h2></div><p>삶의 큰 전환, 선택, 관계의 핵심 주제를 상징하는 카드들이에요.</p></div><div class="card-library-grid">${majorCards.map(cardTile).join('')}</div></section>${minorGroups.map(([suit,group])=>`<section class="card-library-group" id="${suit}"><div class="card-library-group-head"><div><span class="section-kicker">${suitInfo[suit].en}</span><h2>${suitInfo[suit].emoji} ${suitInfo[suit].ko} 14장</h2></div><p>마이너 아르카나 ${suitInfo[suit].ko} 수트의 에이스부터 왕까지 살펴보세요.</p></div><div class="card-library-grid">${group.map(cardTile).join('')}</div></section>`).join('')}</main>`;
await mkdir('dist/cards',{recursive:true});
await writeFile('dist/cards/index.html',page('타로 카드 78장 의미 사전 | 정방향·역방향 해석 · Pick a Card','타로 카드 78장의 뜻을 정방향·역방향, 연애운, 재회운, 상대방 속마음, 연락운, 시기별로 정리한 무료 타로 카드 사전입니다.','/cards/',cardHubBody));
for(const [index,card] of cards.entries()){
 const path=cardPath(card),description=`${card.koreanName}(${card.name}) 타로 카드의 정방향·역방향 뜻과 연애운, 재회운, 상대방 속마음, 연락운, 시기 해석을 정리했습니다.`;
 await mkdir(`dist${path}`,{recursive:true});
 await writeFile(`dist${path}index.html`,page(`${card.koreanName}(${card.name}) 타로 카드 뜻 | 정방향·역방향 해석 · Pick a Card`,description,path,cardDetailBody(card,index)));
}
await mkdir('dist/privacy',{recursive:true});await writeFile('dist/privacy/index.html',page('개인정보 안내 | pick a card','pick a card의 질문 처리와 기기 내 카드 저장 안내','/privacy/',`<main id="main" class="legal info-legal"><section class="info-page"><div class="info-hero"><span class="section-kicker">Privacy</span><h1>개인정보 안내</h1><p>Pick a Card에서 질문과 카드 정보가 어떻게 다뤄지는지 간단히 정리했어요.</p></div><div class="info-grid"><article class="info-card"><span class="info-card-icon" aria-hidden="true">💬</span><div><h2>질문과 계정</h2><p>이 서비스는 계정을 만들거나 이름·이메일을 수집하지 않습니다. 입력한 타로 질문은 브라우저 메모리에서만 사용되며 새로고침하거나 페이지를 떠나면 사라집니다.</p></div></article><article class="info-card"><span class="info-card-icon" aria-hidden="true">📱</span><div><h2>기기에 저장되는 정보</h2><p>오늘의 타로에 한해 카드 ID, 정·역방향, 현지 날짜를 localStorage에 저장합니다. 다음 날 카드를 선택하면 기존 값이 교체됩니다. 브라우저의 사이트 데이터 삭제 기능으로 지울 수 있습니다.</p></div></article><article class="info-card"><span class="info-card-icon" aria-hidden="true">🌐</span><div><h2>접속과 광고</h2><p>서비스 제공을 위한 호스팅 과정에서 IP 주소 등 일반적인 접속 기록이 처리될 수 있습니다. 현재 서비스에는 별도의 분석 스크립트, 광고 스크립트, 생성형 AI API를 연결하지 않았습니다. 광고나 분석 기능이 추가되면 이 안내도 변경합니다.</p></div></article></div><div class="info-footer"><span>최종 업데이트 · 2026년 10월 5일</span><a class="explainer-link" href="/">홈으로 돌아가기 →</a></div></section></main>`));
const extraPages=[['/guide/','타로 가이드','카드의 상징과 리딩을 현실의 질문에 연결하는 일곱 가지 안내.',`<span class="kicker">THE READING ROOM</span><h1>타로 가이드</h1><p class="lead">카드를 이해하고, 내 질문으로 돌아오는 시간.</p><div class="guide-list">${guides.map((g,i)=>`<a href="/guide/${g.slug}/"><span>0${i+1}</span><div><h2>${g.title}</h2><p>${g.intro}</p></div></a>`).join('')}</div>`],['/faq/','자주 묻는 질문','무료 타로의 질문 입력, 반복 리딩, 오늘의 카드와 이용 비용 안내.',`<section class="faq-page-shell"><div class="faq-page-hero"><span class="section-kicker">Questions</span><h1>Pick a Card FAQ</h1><p>이용 방법과 자주 궁금해하는 내용을 한곳에 모았어요.</p></div>${faqList(homeFaq)}<a class="explainer-link faq-guide-link" href="/guide/">타로를 읽는 방법 더 알아보기 →</a></section>`],['/about/','이용 안내 · 서비스 고지','Pick a Card의 카드 구성, 해석 방식과 서비스 범위 안내.',`<section class="info-page"><div class="info-hero"><span class="section-kicker">About Pick a Card</span><h1>Pick a Card 이용 안내</h1><p>카드를 고르는 순간부터 결과를 읽는 방식까지, 서비스가 어떻게 만들어지는지 알려드려요.</p></div><div class="info-grid"><article class="info-card"><span class="info-card-icon" aria-hidden="true">🃏</span><div><h2>한 장의 상징, 여러 관점</h2><p>${cards.length}장의 카드와 ${Object.keys(readings).length}가지 스프레드를 통해 질문을 돌아보는 무료 서비스입니다. 가입이나 결제가 필요하지 않습니다.</p></div></article><article class="info-card"><span class="info-card-icon" aria-hidden="true">🎴</span><div><h2>리딩은 어떻게 만들어지나요?</h2><p>브라우저의 보안 난수로 ${cards.length}장을 섞고 정·역방향을 정합니다. 카드를 직접 고르면 미리 작성한 의미와 주제·위치별 문장을 연결합니다. 전체 흐름은 뽑힌 모든 카드의 의미 태그와 위치를 함께 살피고, 반복되는 주제와 갈등·계기를 연결하는 규칙으로 작성됩니다. 입력한 질문을 분석하거나 생성형 AI를 호출하지 않습니다.</p></div></article><article class="info-card"><span class="info-card-icon" aria-hidden="true">🧭</span><div><h2>리딩의 범위</h2><p>불편한 해석을 내 상황에 억지로 맞출 필요는 없습니다. 실제 대화, 상대의 동의, 자신의 경험을 우선하세요.</p></div></article><article class="info-card"><span class="info-card-icon" aria-hidden="true">☀️</span><div><h2>오늘의 카드와 광고</h2><p>오늘의 카드는 기기의 현지 날짜를 기준으로 같은 브라우저에 보관합니다. 현재 광고와 유료 상담은 제공하지 않습니다.</p></div></article></div><div class="info-footer"><span>Pick a Card · ${Object.keys(readings).length} readings</span><a class="explainer-link" href="/privacy/">개인정보 처리 방식 읽기 →</a></div></section>`],...guides.map(g=>[`/guide/${g.slug}/`,g.title,g.intro,`<article class="guide-detail"><a class="back-link" href="/guide/">← 타로 가이드</a><div class="guide-hero"><span class="kicker">PICK A CARD · READING NOTES</span><h1>${g.title}</h1><p class="lead">${g.intro}</p></div><div class="guide-article">${g.sections.map(([h,p],i)=>`<section class="guide-section"><span class="guide-section-number">${String(i+1).padStart(2,'0')}</span><div><h2>${h}</h2><p>${p}</p></div></section>`).join('')}</div><aside class="guide-next"><div><span class="guide-next-icon" aria-hidden="true">${readingEmoji[g.related]||'🔮'}</span><div><strong>이 관점으로 카드를 펼쳐보세요.</strong><p>${readings[g.related].name} 리딩으로 이어서 살펴볼 수 있어요.</p></div></div><a class="button primary" href="/tarot/${g.related}/">${readings[g.related].name} 보기 →</a></aside></article>`])];
for(const [path,title,description,body] of extraPages){await mkdir(`dist${path}`,{recursive:true});await writeFile(`dist${path}index.html`,page(`${title} | Pick a Card`,description,path,`<main id="main" class="legal guide-page">${body}</main>`));}
await writeFile('dist/404.html',page('페이지를 찾을 수 없어요 | pick a card','무료 타로 홈으로 돌아가세요.','/404',`<main id="main" class="legal"><h1>이 카드는 아직 없네요.</h1><p>주소를 확인하거나 다른 타로를 골라주세요.</p><a class="button primary" href="/">홈으로 돌아가기</a></main>`));
const urls=['/',...Object.keys(readings).map(s=>`/tarot/${s}/`),'/cards/',...cards.map(cardPath),'/privacy/',...extraPages.map(p=>p[0])];await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')}</urlset>`);await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${urls.length} static pages with unique metadata.`);

// Version every static dependency so a prior open tab cannot retain a stale deck module.
async function filesUnder(dir){const paths=[];for(const entry of await readdir(dir,{withFileTypes:true})){const path=`${dir}/${entry.name}`;if(entry.isDirectory())paths.push(...await filesUnder(path));else paths.push(path);}return paths.sort();}
const digest=createHash('sha256');for(const path of [...await filesUnder('src'),...await filesUnder('public')]){digest.update(path);digest.update(await readFile(path));}
const assetVersion=digest.digest('hex').slice(0,12);
for(const path of await filesUnder('dist')){
 if(path.endsWith('.mjs')){let source=await readFile(path,'utf8');source=source.replace(/from (['"])(\.\.?\/[^'"?]+\.mjs)\1/g,(_,quote,url)=>`from ${quote}${url}?v=${assetVersion}${quote}`);if(path.endsWith('/card-view.mjs'))source=source.replaceAll('.webp','.webp?v='+assetVersion);await writeFile(path,source);}
 else if(path.endsWith('.html')){const source=await readFile(path,'utf8');await writeFile(path,source.replaceAll('/style.css"',`/style.css?v=${assetVersion}"`).replaceAll('/src/app.mjs"',`/src/app.mjs?v=${assetVersion}"`));}
}


// GitHub Pages project-site base path support. Keep source templates root-based for local/dev builds,
// then prefix only root-relative browser references in the built artifact.
if(publicBase){
 const prefixBuiltReferences=source=>source
  .replaceAll('href="/',`href="${publicBase}/`)
  .replaceAll('src="/',`src="${publicBase}/`)
  .replaceAll('srcset="/',`srcset="${publicBase}/`)
  .replaceAll(', /artwork/',`, ${publicBase}/artwork/`)
  .replaceAll("url('/",`url('${publicBase}/`)
  .replaceAll('url("/',`url("${publicBase}/`);
 for(const path of await filesUnder('dist')){
  if(/\.(html|mjs|css)$/.test(path)){
   const source=await readFile(path,'utf8');
   await writeFile(path,prefixBuiltReferences(source));
  }
 }
}
