import {mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {readings,primary,secondary,disclaimer} from '../src/data/readings.mjs';
const origin=process.env.SITE_URL||'https://pickacard.jijiminseo.chatgpt.site';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const faq=items=>`<div class="faq">${items.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div>`;
const tile=(slug,small=false)=>{const r=readings[slug];return `<a class="reading-tile ${r.color} ${small?'small':''}" href="/tarot/${slug}/"><span class="tile-top"><span>${r.name}</span><span class="pill">${slug==='yes-no'?'1–3':r.positions.length} CARDS</span></span><span class="tile-art" aria-hidden="true"><span>${r.mark}</span></span><span class="tile-bottom">${r.tagline}<span aria-hidden="true">＋</span></span></a>`};
const footer=`<footer><a class="brand" href="/">pick a card<span class="brand-star">✳</span></a><p>답을 찾는 순간, 나를 들여다보는 시간.</p><p class="disclaimer">${disclaimer}</p><div class="footer-bottom"><span>© ${new Date().getFullYear()} pick a card</span><a href="/privacy/">개인정보 안내</a><span>한국어</span></div></footer>`;
const page=(title,description,path,body,faqs=[])=>`<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin}${path}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:url" content="${origin}${path}"><meta name="theme-color" content="#fafafa"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#23272b"/><path d="M16 6v20M6 16h20M9 9l14 14M23 9L9 23" stroke="#f1b5c7" stroke-width="3"/></svg>')}"><link rel="stylesheet" href="/style.css">${faqs.length?`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}).replace(/</g,'\\u003c')}</script>`:''}</head><body><a class="skip" href="#main">본문으로 건너뛰기</a><header><a href="/" class="brand" aria-label="pick a card 홈">pick a card<span class="brand-star">✳</span></a><nav aria-label="주 메뉴"><a href="/#readings">모든 타로</a><a href="/tarot/today/">오늘의 카드 <span aria-hidden="true">☼</span></a></nav></header>${body}${footer}<script type="module" src="/src/app.mjs"></script></body></html>`;
const homeFaq=[['정말 무료인가요?','모든 리딩은 가입이나 결제 없이 무료로 볼 수 있습니다. 카드를 선택하면 미리 작성된 상징 해석을 조합해 보여드립니다.'],['카드는 어떻게 뽑히나요?','브라우저의 보안 난수로 22장의 카드를 섞습니다. 각 카드는 동일한 추첨 기회를 가지며 한 번의 리딩에서는 같은 카드가 중복되지 않습니다. 정방향과 역방향도 무작위로 정합니다.'],['질문을 꼭 입력해야 하나요?','대부분의 타로는 마음속으로 떠올리기만 해도 됩니다. YES/NO 타로에서만 질문을 입력합니다. 입력한 내용은 외부로 전송하거나 저장하지 않습니다.'],['원하는 답이 나올 때까지 다시 뽑아도 되나요?','여러 번 뽑는다고 결과가 더 정확해지지는 않습니다. 한 번의 리딩에서 생각해 볼 질문을 찾는 편이 도움이 됩니다. 오늘의 카드는 같은 날 유지됩니다.']];
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('src','dist/src',{recursive:true});await cp('public','dist',{recursive:true});
await writeFile('dist/index.html',page('무료 타로 · 연애운, 재회운, 이별운, 속마음 | pick a card','지금 마음에 남는 질문 하나. 연애운, 재회운, 이별운, 상대방 속마음부터 오늘의 타로까지, 직접 고르는 8가지 무료 타로.','/',`<main id="main"><section class="home-intro"><div class="kicker"><span class="little-star">✳</span> A LITTLE CLARITY, JUST FOR YOU</div><h1>지금 가장 궁금한 것은<br>무엇인가요<span class="pink-dot">?</span></h1><p>마음에 남는 질문 하나, 그리고 당신이 고른 카드.<br>조금 다른 시선으로 지금의 마음을 읽어보세요.</p><div class="quiet-label">가입 없이 · 언제나 무료</div></section><section id="readings" class="readings-section"><div class="section-heading"><h2>마음이 향하는 질문</h2><span>LOVE & RELATIONSHIPS</span></div><div class="primary-grid">${primary.map(s=>tile(s)).join('')}</div><div class="section-heading secondary-heading"><h2>조금 더 궁금하다면</h2><span>A LITTLE MORE</span></div><div class="secondary-grid">${secondary.map(s=>tile(s,true)).join('')}</div></section><section class="how"><div><span class="kicker">YOUR MOMENT</span><h2>잠깐 멈추고,<br>한 장씩 천천히.</h2></div><ol><li><span>01</span><div><h3>질문을 떠올려요</h3><p>정답보다 지금 궁금한 마음에 집중해요.</p></div></li><li><span>02</span><div><h3>끌리는 카드를 골라요</h3><p>정해진 방법 없이, 당신의 속도로.</p></div></li><li><span>03</span><div><h3>나의 이야기로 읽어요</h3><p>미래의 확정이 아닌, 나를 위한 작은 힌트.</p></div></li></ol></section><section class="about"><span class="kicker">ABOUT THE READING</span><h2>미래를 정하는 답보다,<br>지금을 이해하는 질문.</h2><p>pick a card는 메이저 아르카나 22장의 상징으로 나와 관계를 돌아보는 무료 타로입니다. 주제마다 다른 스프레드와 해석을 제공하며, 카드의 정·역방향을 함께 읽습니다. 상대의 마음이나 미래를 사실처럼 단정하지 않아요.</p></section><section class="faq-section"><div class="section-heading"><h2>자주 묻는 질문</h2><span>GOOD TO KNOW</span></div>${faq(homeFaq)}</section></main>`,homeFaq));
for(const [slug,r] of Object.entries(readings)){
const path=`/tarot/${slug}/`;await mkdir(`dist${path}`,{recursive:true});
const body=`<main id="main" data-reading="${slug}"><a class="back-link" href="/">모든 타로</a><section class="reading-intro"><span class="kicker">${r.eyebrow}</span><h1>${r.name}</h1><p class="lead">${r.tagline}</p><p>${r.intro}</p><div class="reading-meta"><span>${slug==='yes-no'?'1–3':r.positions.length}장의 카드</span><span>무료 리딩</span><span>정·역방향</span></div></section><div class="ad-slot" data-ad-placement="before-selection" hidden></div><section id="reading-app" aria-label="카드 리딩"><form id="question-form" class="question-panel"><div class="panel-heading"><span class="step-label">01 / YOUR QUESTION</span><h2>질문을 천천히 떠올려 주세요.</h2><p>${r.question}</p></div>${slug!=='today'?`<label for="question">나의 질문 <span>${slug==='yes-no'?'필수':'선택 · 마음속으로 떠올려도 좋아요'}</span></label><textarea id="question" name="question" maxlength="300" rows="2" placeholder="${r.question}" ${slug==='yes-no'?'required':''}></textarea><p class="privacy-note">질문은 저장하거나 외부로 전송하지 않아요.</p>`:''}${slug==='yes-no'?'<fieldset><legend>몇 장의 카드를 뽑을까요?</legend><div class="count-options">'+[1,2,3].map(n=>`<label><input type="radio" name="count" value="${n}" ${n===3?'checked':''}><span>${n}장</span></label>`).join('')+'</div></fieldset>':''}<button class="button primary" type="submit">${slug==='today'?'오늘의 카드 만나기':'카드 고르기'}<span aria-hidden="true">✳</span></button><p id="form-error" role="alert"></p></form><noscript><p>카드 선택에는 JavaScript가 필요합니다. 아래에서 스프레드 안내와 자주 묻는 질문을 읽을 수 있습니다.</p></noscript></section><section class="spread-info"><span class="kicker">THE SPREAD</span><h2>${r.name}, 이렇게 읽어요</h2><p>${r.explanation}</p><ol>${r.positions.map((p,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><div><h3>${p.label}</h3><p>${p.lens}</p></div></li>`).join('')}</ol></section><section class="faq-section"><h2>${r.name} 자주 묻는 질문</h2>${faq(r.faq)}</section></main>`;
await writeFile(`dist${path}index.html`,page(`${r.name} 무료 타로 | ${r.tagline} · pick a card`,r.description,path,body,r.faq));}
await mkdir('dist/privacy',{recursive:true});await writeFile('dist/privacy/index.html',page('개인정보 안내 | pick a card','pick a card의 질문 처리와 기기 내 카드 저장 안내','/privacy/',`<main id="main" class="legal"><h1>개인정보 안내</h1><p>이 서비스는 계정을 만들거나 이름·이메일을 수집하지 않습니다. 입력한 타로 질문은 브라우저 메모리에서만 사용되며 새로고침하거나 페이지를 떠나면 사라집니다.</p><h2>기기에 저장되는 정보</h2><p>오늘의 타로에 한해 카드 ID, 정·역방향, 현지 날짜를 localStorage에 저장합니다. 다음 날 카드를 선택하면 기존 값이 교체됩니다. 브라우저의 사이트 데이터 삭제 기능으로 지울 수 있습니다.</p><h2>접속과 광고</h2><p>서비스 제공을 위한 호스팅 과정에서 IP 주소 등 일반적인 접속 기록이 처리될 수 있습니다. 현재 서비스에는 별도의 분석 스크립트, 광고 스크립트, 생성형 AI API를 연결하지 않았습니다. 광고나 분석 기능이 추가되면 이 안내도 변경합니다.</p><h2>리딩 이용 안내</h2><p>${disclaimer}</p><p>최종 업데이트: 2026년 10월 4일</p><a href="/">홈으로 돌아가기</a></main>`));
await writeFile('dist/404.html',page('페이지를 찾을 수 없어요 | pick a card','무료 타로 홈으로 돌아가세요.','/404',`<main id="main" class="legal"><h1>이 카드는 아직 없네요.</h1><p>주소를 확인하거나 다른 타로를 골라주세요.</p><a class="button primary" href="/">홈으로 돌아가기</a></main>`));
const urls=['/',...Object.keys(readings).map(s=>`/tarot/${s}/`),'/privacy/'];await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')}</urlset>`);await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${urls.length} static pages with unique metadata.`);
