// Editorial components shared by the static page builder.
export const readingArtwork = {love:'lovers', reunion:'cups-6', breakup:'major-13', feelings:'moon', contact:'cups-11', 'reunion-timing':'major-10', 'yes-no':'major-11', today:'sun', job:'wands-1', money:'pentacles-1', work:'pentacles-3', study:'major-9'};
export const hero = `<section class="home-intro"><div class="hero-copy"><span class="kicker">A QUIET MOMENT, JUST FOR YOU</span><h1>마음에 걸리는<br>질문이 있나요?</h1><p>서두르지 않아도 괜찮아요.<br>마음이 가는 카드를 고르고,<br class="mobile-break"> 지금의 나를 천천히 읽어보세요.</p><div class="hero-actions"><a class="button primary" href="#readings">나의 질문 고르기 <span aria-hidden="true">↗</span></a><a class="text-link" href="/tarot/today/">오늘의 카드 한 장 →</a></div><div class="quiet-label">78장의 카드 <i></i> 12가지 리딩 <i></i> 가입 없이 무료</div></div><div class="hero-deck" aria-label="Pick a Card의 태양, 연인 카드와 버건디 카드 뒷면"><span class="deck-orbit" aria-hidden="true"></span><div class="hero-card hero-card-back"><img src="/artwork/card-back.svg" width="192" height="288" alt="Pick a Card 카드 뒷면"></div><div class="hero-card hero-card-sun"><span>XIX · THE SUN</span><img src="/artwork/sun.webp" width="384" height="576" alt="태양 카드"><small>기쁨을 발견하는 마음</small></div><div class="hero-card hero-card-lovers"><span>VI · THE LOVERS</span><img src="/artwork/lovers.webp" width="384" height="576" alt="연인 카드"><small>마음이 향하는 곳</small></div><span class="deck-caption">A LITTLE CLARITY, ONE CARD AT A TIME.</span></div></section>`;
export const dailyFeature = `<aside class="daily-feature"><img src="/artwork/card-back.svg" width="80" height="120" loading="lazy" alt=""><div><span class="kicker">ONE CARD, ONE DAY</span><h2>오늘의 나에게, 한 장.</h2><p>어떤 하루든, 잠깐 나를 돌아보는 시간은 필요하니까요.</p></div><a class="button primary" href="/tarot/today/">오늘의 카드 만나기 ↗</a></aside>`;
export function guideVisual(slug) {
 if(slug==='upright-reversed') return `<div class="guide-visual orientation-visual"><figure><img src="/artwork/sun.webp" width="192" height="288" alt="정방향 태양 카드"><figcaption><span>UPRIGHT</span><strong>자연스럽게 드러나는 힘</strong><p>태양의 밝음과 즐거움을 나누는 관점</p></figcaption></figure><figure><img class="reversed-art" src="/artwork/sun.webp" width="192" height="288" alt="역방향 태양 카드"><figcaption><span>REVERSED</span><strong>한 번 더 살펴보는 힘</strong><p>밝아야 한다는 부담은 없는지 살피는 관점</p></figcaption></figure></div>`;
 if(['major-arcana','minor-arcana'].includes(slug)) {
 const major=slug==='major-arcana';const items=major?[['fool','시작'],['lovers','선택'],['tower','변화'],['major-21','완성']]:[['wands-1','완드 · 행동'],['cups-1','컵 · 감정'],['swords-1','소드 · 생각'],['pentacles-1','펜타클 · 생활']];
 return `<div class="guide-visual suit-visual">${items.map(([file,name])=>`<figure><img src="/artwork/${file}-small.webp" width="192" height="288" loading="lazy" alt="${name}"><figcaption>${name}</figcaption></figure>`).join('')}</div>`;
 }
 if(slug==='better-questions')return `<div class="question-comparison"><div><span>막연한 질문</span><p>앞으로 잘될까요?</p></div><span aria-hidden="true">→</span><div><span>내가 살펴볼 수 있는 질문</span><p>지금 시작하기 위해<br>무엇을 준비하면 좋을까요?</p></div></div>`;
 return '';
}
