import {cardNumber,cardArt,cardFace} from './card-view.mjs';
import {cards} from './data/cards.mjs';
import {readings} from './data/readings.mjs';
import {shuffleDeck,loadDaily,saveDaily,dateKey,interpret,verdict,synthesis,generalAdvice} from './engine.mjs';
document.addEventListener('error',event=>{if(event.target instanceof HTMLImageElement&&event.target.closest('.artwork-holder')){event.target.hidden=true;event.target.parentElement.classList.add('image-failed');}},true);
const root=document.querySelector('[data-reading]');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const legacyRoman=n=>['0','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'][n]||String(n);
if(root){
 const slug=root.dataset.reading,r=readings[slug],app=document.querySelector('#reading-app');
 let deck=[],selected=[],count=r.positions.length,question='',phase='question',drawingDate=null,timer=null,storage=null;
 try{storage=window.localStorage;}catch{}
 const formHTML=app.innerHTML;
 function focusHeading(){const heading=app.querySelector('h2');if(heading){heading.tabIndex=-1;heading.classList.add('result-focus');heading.focus({preventScroll:true});app.scrollIntoView?.({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}}
 function attachForm(){app.querySelector('form').addEventListener('submit',e=>{e.preventDefault();question=app.querySelector('#question')?.value.trim()||'';if(slug==='yes-no'&&!question){app.querySelector('#form-error').textContent='질문을 먼저 입력해 주세요.';app.querySelector('#question').focus();return;}count=slug==='yes-no'?Number(new FormData(e.currentTarget).get('count')):r.positions.length;start();});}
 function start(){if(slug==='today'){const saved=loadDaily(storage);if(saved){selected=[saved];showResults(true);return;}}deck=shuffleDeck();selected=[];drawingDate=dateKey();phase='selecting';app.innerHTML=`<div class="selection-heading"><span class="step-label">02 / PICK YOUR CARDS</span><h2>마음이 가는 카드를 골라주세요.</h2><p id="selection-status" role="status" aria-live="polite">${count}장 중 0장 선택 · ${r.positions[0].label}</p><div class="progress-dots" aria-hidden="true">${Array.from({length:count},()=>'<span></span>').join('')}</div></div><div class="deck" aria-label="섞인 카드 ${deck.length}장">${deck.map((_,i)=>`<button class="card-button" type="button" data-index="${i}" aria-label="${i+1}번째 카드 선택" aria-pressed="false"><span class="card-inner"><span class="card-back" aria-hidden="true"></span><span class="card-front" aria-hidden="true"></span></span></button>`).join('')}</div><div class="picked-list" aria-label="선택한 카드"></div><p class="selection-note">카드는 이미 섞여 있어요. 정답인 위치는 없으니 천천히 골라주세요.</p>`;app.querySelectorAll('.card-button').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.index))));focusHeading();}
 function select(index){if(phase!=='selecting'||!Number.isInteger(index)||index<0||index>=deck.length||selected.some(s=>s.index===index)||selected.length>=count)return false;const pick={...deck[index],index};selected.push(pick);const card=cards.find(c=>c.id===pick.id),button=app.querySelector(`[data-index="${index}"]`);button.disabled=true;button.setAttribute('aria-pressed','true');button.setAttribute('aria-label',`${card.koreanName}, ${pick.reversed?'역방향':'정방향'}, 선택됨`);button.querySelector('.card-front').innerHTML=`<span class="card-number">${cardNumber(card)}</span>${cardArt(card,pick.reversed)}<strong>${card.koreanName}</strong><small>${pick.reversed?'역방향':'정방향'}</small>`;button.classList.add('is-selected');button.querySelector('.card-front').classList.toggle('is-reversed',pick.reversed);app.querySelector('.picked-list').insertAdjacentHTML('beforeend',`<span>${selected.length}. ${r.positions[selected.length-1].label} · ${card.koreanName}</span>`);app.querySelectorAll('.progress-dots span').forEach((d,i)=>d.classList.toggle('filled',i<selected.length));app.querySelector('#selection-status').textContent=`${count}장 중 ${selected.length}장 선택${selected.length<count?' · 다음: '+r.positions[selected.length].label:' · 선택한 카드의 이야기를 준비하고 있어요.'}`;if(selected.length===count){phase='revealing';app.querySelectorAll('.card-button').forEach(b=>b.disabled=true);timer=setTimeout(()=>showResults(false),750);}return true;}
 function cardSummary(){return `<div class="card-summary" tabindex="0" role="region" aria-label="선택한 카드 요약, 가로로 스크롤할 수 있습니다">${selected.map((pick,i)=>{const c=cards.find(c=>c.id===pick.id);return `<div class="summary-item">${cardFace(c,pick.reversed)}<p>${i+1}. ${pick.reversed?'역방향':'정방향'}</p></div>`}).join('')}</div>`;}
 function positionResult(pick,i){const {card,position,meaning,context,lens,caution}=interpret(slug,pick,i);return `<article class="result-position"><div class="detail-card" aria-hidden="true">${cardFace(card,pick.reversed)}</div><div class="result-title"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${position.label}</h3><p class="card-meta">${card.koreanName} · ${card.name} · ${pick.reversed?'역방향':'정방향'}</p></div></div><div class="keywords">${card.keywords.map(k=>`<span>${k}</span>`).join('')}</div><p>${meaning}</p><p>${context}</p>${slug==='yes-no'?`<p class="lens">이 카드의 방향성: ${pick.reversed?'역방향이므로 실행보다 조건 재점검을 우선하는 신호로 반영했습니다.':card.yesNo>0?'시도와 개방을 나타내는 상징으로 YES 쪽에 반영했습니다.':card.yesNo<0?'멈춤과 재정비를 나타내는 상징으로 NO 쪽에 반영했습니다.':'조건과 관찰이 필요한 중립의 상징으로 반영했습니다.'}</p>`:''}<p class="lens">${lens}</p>${caution?`<p class="caution">${caution}</p>`:''}</article>`;}
 function dailyResult(){const pick=selected[0],c=cards.find(c=>c.id===pick.id);return `<div class="daily-grid">${[['오늘의 전체 흐름',`‘${c.keywords.join(' · ')}’을 오늘의 관점으로 삼아보세요. ${pick.reversed?c.reversed:c.upright}로 읽을 수 있습니다.`],['연애',pick.reversed?`오늘은 ${c.reversed}로 읽습니다. ${c.advice}`:c.love],['일 / 학업',`${generalAdvice(c,pick.reversed)} 업무나 공부에서는 이 조언을 오늘 끝낼 작은 과제 하나에 적용해 보세요.`],['금전',`‘${c.keywords[0]}’ 키워드가 나의 소비 태도와 어떻게 닿는지 돌아보세요. 수익이나 손실의 예고가 아니며, 지출은 실제 예산을 확인한 뒤 결정하세요.`],['오늘의 조언',generalAdvice(c,pick.reversed)]].map(([title,text])=>`<article class="result-position"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`;}
 const readingEmoji={love:'💗',reunion:'🔁',breakup:'🥀',feelings:'💭',contact:'💌','reunion-timing':'⏳','yes-no':'🔮',today:'☀️',job:'💼',money:'💰',work:'🧑‍💻',study:'📚'};
const relatedPrompts={feelings:'그 사람의 현재 마음이 궁금한가요?',contact:'연락이 다시 올지 궁금한가요?','reunion-timing':'관계가 움직이는 계기가 궁금한가요?',reunion:'다시 연결될 여지를 살펴볼까요?',love:'나에게 필요한 사랑은 어떤 모습일까요?',today:'오늘의 나에게 한 장을 건네볼까요?','yes-no':'가볍게 떠오르는 질문이 있나요?',job:'다음 기회를 어떻게 준비하면 좋을까요?',money:'지금 돈의 흐름을 점검해볼까요?',work:'현재 직장과 커리어 흐름이 궁금한가요?',study:'공부에서 어디에 힘을 써야 할까요?'};
 function showResults(restored){clearTimeout(timer);let warning='';if(slug==='today'&&!restored){if(drawingDate!==dateKey()){app.innerHTML='<p class="storage-warning">날짜가 바뀌었어요. 새로운 하루의 카드를 골라주세요.</p>'+formHTML;phase='question';attachForm();return;}const existing=loadDaily(storage);if(existing){selected=[existing];restored=true;}else if(!saveDaily(storage,{id:selected[0].id,reversed:selected[0].reversed}))warning='이 브라우저에서 저장을 사용할 수 없어 새로고침 시 카드가 유지되지 않을 수 있어요.';}phase='result';app.innerHTML=`<div class="results-heading"><span class="step-label">${slug==='today'?dateKey():'03 / YOUR READING'}</span><h2>${slug==='today'?'오늘, 당신에게 온 카드':'당신이 고른 카드의 이야기'}</h2><p>${slug==='today'?(restored?'오늘의 카드를 다시 펼쳤어요.':'오늘 하루, 이 메시지를 기억해 보세요.'):'카드의 상징을 지금의 상황에 비추어 읽어보세요.'}</p>${question?`<p class="question-echo">${esc(question)}</p>`:''}</div>${warning?`<p class="storage-warning" role="status">${warning}</p>`:''}${cardSummary()}${slug==='yes-no'?`<section class="verdict"><span class="step-label">SYMBOLIC DIRECTION</span><h3>${verdict(selected)}</h3><p>아래 카드의 상징과 방향을 종합한 참고 메시지입니다. 상반된 신호가 섞이면 판단을 유보합니다. 정답이나 성공 확률이 아닙니다.</p></section>`:''}${slug==='today'?dailyResult():selected.map((pick,i)=>positionResult(pick,i)+(i===1?'<div class="ad-slot" data-ad-placement="result-middle" hidden></div>':'')).join('')}<section class="synthesis"><span class="step-label">${slug==='today'?'TAKE IT WITH YOU':'THE BIG PICTURE'}</span><h2>${slug==='today'?'오늘 가져갈 한 문장':'전체 흐름을 함께 읽으면'}</h2>${(slug==='today'?[generalAdvice(cards.find(c=>c.id===selected[0].id),selected[0].reversed),r.summary]:synthesis(slug,selected)).map(t=>`<p>${t}</p>`).join('')}</section><div class="ad-slot" data-ad-placement="result-bottom" hidden></div><section class="related"><h2>${['job','money','work','study'].includes(slug)?'다른 고민도 살펴볼까요':'이 마음이 더 궁금하다면'}</h2>${r.related.map(s=>`<a href="/tarot/${s}/"><span class="related-icon" aria-hidden="true">${readingEmoji[s]||readings[s].mark}</span><span>${relatedPrompts[s]}</span><strong>${readings[s].name} ＋</strong></a>`).join('')}</section><div class="result-actions"><a class="button primary" href="/">다른 타로 고르기</a>${slug==='today'?'':'<button class="button secondary" id="restart" type="button">새로운 질문으로 보기</button>'}</div>`;app.querySelector('#restart')?.addEventListener('click',()=>{phase='question';selected=[];question='';app.innerHTML=formHTML;attachForm();focusHeading();});focusHeading();}
 attachForm();if(slug==='today'){const saved=loadDaily(storage);if(saved){selected=[saved];showResults(true);}}
 window.addEventListener('storage',e=>{if(slug==='today'&&e.key==='pickacard:daily:v1'&&phase==='result'){const saved=loadDaily(storage);if(saved){selected=[saved];showResults(true);}}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&slug==='today'&&phase==='result'&&!loadDaily(storage)){app.innerHTML=formHTML;phase='question';attachForm();}});
 const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'get_tarot_reading_state',description:'Read the currently visible tarot stage and revealed cards; does not draw cards or disclose unselected cards.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('Expected an empty object');return {type:slug,phase,selectedCount:selected.length,requiredCount:count,cards:selected.map(({id,reversed})=>({id,reversed}))};}})).catch(()=>{});}catch{}}
}
